development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgressql
  url: postgres://vaeomdlygwjyie:958c9d00dbfadf8c6dc45e185f24bc5feb5147034f64ad1c4c7fcf223184cd10@ec2-50-17-206-214.compute-1.amazonaws.com:5432/d1ge45pspkn81r
  channel_prefix: ArtStore_production
